apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Patches to override base configuration for local environment
patches:
  - path: configmap.yaml

namePrefix: local-
