apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: load-tester

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: frontend
  app.kubernetes.io/component: load-tester
  app.kubernetes.io/managed-by: kustomize
